name: Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Enable Corepack
        working-directory: ./web
        run: corepack enable

      - name: Setup Node/Yarn environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "yarn"
          cache-dependency-path: ./web/yarn.lock

      - name: Install web
        run: yarn install
        working-directory: ./web

      - name: Build web with Yarn
        run: yarn build
        working-directory: ./web

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

      - name: Test Backend
        # TestFollow fails to work in GitHub Actions. Likely a result of permissions. Will investigate further later
        run: go test -race -covermode=atomic -coverprofile=coverage.txt -v -skip TestFollow ./...

      - name: Test Frontend
        working-directory: ./web
        run: yarn coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
