name: Build and Test logstation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          cache: 'yarn'

      - name: Install web
        run: yarn install

      - name: Build web with Yarn
        run: yarn --cwd web build

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...