name: Build and Test logstation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  YARN_IGNORE_PATH: 1 # .yarnrc specifies yarn-3.5.0.cjs which GitHub Actions has trouble finding. Use default yarn

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.x'
          cache: 'yarn'
          cache-dependency-path: ./web/yarn.lock

      - name: Install web
        run: yarn install --frozen-lockfile
        working-directory: ./web

      - name: Build web with Yarn
        run: yarn build
        working-directory: ./web

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v ./...

      - name: Test
        # TestFollow fails to work in GitHub Actions. Likely a result of permissions. Will investigate further later
        run: go test -v -skip TestFollow ./...
