name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tag the release
        run: git tag ${{ github.event.inputs.tag }}

      - name: Enable Corepack
        working-directory: ./web
        run: corepack enable
        with:
          node-version: '20.x'

      - name: Setup Node/Yarn environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "yarn"
          cache-dependency-path: ./web/yarn.lock

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}